# Generated by Django 5.0.6 on 2024-06-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='laboratory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(related_name='researchers', to='laboratory.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='laboratory.researcher'),
        ),
    ]
