# Generated by Django 5.0.6 on 2024-06-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='laboratory.researcher'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='researchers', to='laboratory.project'),
        ),
    ]
